### ISSUE TITLE
webman 切面初始化的时候 可以放到bootstarp中吗

### ISSUE THREAD

**Issue by hon94csl** [marxphp/aop#2]
现在直接修改start.php 感觉不太好，框架更新这个代码就不在了，
能否把初始化放到 webman 的bootstartp 执行：如下

- 添加引导配置
![image](https://user-images.githubusercontent.com/15683014/197479426-a7f52a95-71d9-4ffe-8c96-4b611bf6e2da.png)
- 创建引导类
![image](https://user-images.githubusercontent.com/15683014/197479720-499175cf-c16a-4b41-99c8-75f2f49b7ae6.png)

我做了以上尝试，但是会有一个错误 （加载文件确实是存在的）
![image](https://user-images.githubusercontent.com/15683014/197483068-cd82ad5a-c042-4245-a1bd-571910f3ad44.png)

**Comment by bbuugg** [comment]
不建议放进bootstrap.php中，看了下webman源码，bootstrap在workerStart阶段执行，aop会fork新的进程来处理，可能会有问题。尽量放在代码最开始，因为这样可以保证大部分类可以被切入。看你上面这个截图应该是IndexController里面有使用__DIR__这个魔术常量导致的，因为代理类的目录和app目录不一致的问题，所以尽量使用BASE_PATH等初始化时定义的常量。这个问题后面看看怎么修复。另外虽然发布了版本，但是依然不建议成产使用。

**Comment by hon94csl** [comment]
> 

当前1.2版本还有什么bug没有修复吗，我打算用在正式项目里面

**Comment by bbuugg** [comment]
建议用hyperf的aop，毕竟经过大量验证，有专门的团队维护。

**Comment by hon94csl** [comment]
> 

hyperf的aop之前调研个一下，不支持php8的注解 所以选的你这个，我主要是用在权限验证这块，按你这么说我还是先用中间件实现比较靠谱
